apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: {{ .Values.backendImage.name }}
      - image: {{ .Values.backendImage.repository }}
      - containerPort: 80
